% This function facilitates the wall-normal extrusion of a 2D mesh domain 
% with O-grid topology. 
%       Author          : John Watchorn
%       Version         : 1
% Inputs:
%       ID              -> Allocated ID of extruded mesh output
%       ID_CN           -> Input IDs of connectors forming the wall boundary
%       initStep        -> Initial mesh layer height [m]
%       growthFactor    -> Growth factor
%       numLayers       -> Number of mesh layers (away from the wall)
%       explSmooth      -> Explicit smoothing parameter
%       implSmooth      -> Implicit smoothing parameter
%       kbSmooth        -> Kinsey Barth parameter
%       volSmooth       -> Volume smoothing parameter
% Outputs:
%       extrudeCommand  -> String containing the wall-normal mesh extrusion
%                          command. 
function extrudeCommand = pwExtrude(ID,ID_CN,initStep,growthFactor,numLayers,explSmooth,implSmooth,kbSmooth,volSmooth)
    connectorString = append('[list');
    for i = 1:length(ID_CN)
        if i < length(ID_CN)
            connectorString = append(connectorString,' $_CN(',num2str(ID_CN(i)),')');
        else
            connectorString = append(connectorString,' $_CN(',num2str(ID_CN(i)),')]');
        end
    end

    extrudeCommand = append(['set _TMP(mode_1) [pw::Application begin Create]\n'...
        '    set _TMP(PW_1) [pw::Edge createFromConnectors ',connectorString,']\n'...
        '    set _TMP(edge_1) [lindex $_TMP(PW_1) 0]\n'...
        '    unset _TMP(PW_1)\n'...
        '    set _DM(',num2str(ID),') [pw::DomainStructured create]\n'...
        '    $_DM(',num2str(ID),') addEdge $_TMP(edge_1)\n'...
        '$_TMP(mode_1) end\n'...
        'unset _TMP(mode_1)\n'...
        'set _TMP(mode_1) [pw::Application begin ExtrusionSolver [list $_DM(',num2str(ID),')]]\n'...
        '    $_TMP(mode_1) setKeepFailingStep false\n'...
        '    $_DM(',num2str(ID),') setExtrusionSolverAttribute SpacingMode Algebraic\n'...
        '    $_DM(',num2str(ID),') setExtrusionSolverAttribute NormalInitialStepSize ',num2str(initStep),'\n'...
        '    $_DM(',num2str(ID),') setExtrusionSolverAttribute SpacingGrowthFactor ',num2str(growthFactor),'\n'...
        '    $_DM(',num2str(ID),') setExtrusionSolverAttribute NormalMarchingVector {-0 -0 -1}\n'...
        '    $_DM(',num2str(ID),') setExtrusionSolverAttribute StopAtPositiveSkewJacobian true\n'...
        '    $_DM(',num2str(ID),') setExtrusionSolverAttribute StopAtZeroJacobian true\n'...
        '    $_DM(',num2str(ID),') setExtrusionSolverAttribute StopAtNegativeJacobian true\n'...
        '    $_DM(',num2str(ID),') setExtrusionSolverAttribute StopAtNegativeSkewJacobian true\n'...
        '    $_DM(',num2str(ID),') setExtrusionSolverAttribute Mode NormalHyperbolic\n'...
        '    $_DM(',num2str(ID),') setExtrusionSolverAttribute NormalExplicitSmoothing ',num2str(explSmooth),'\n'...
        '    $_DM(',num2str(ID),') setExtrusionSolverAttribute NormalImplicitSmoothing ',num2str(implSmooth),'\n'...
        '    $_DM(',num2str(ID),') setExtrusionSolverAttribute NormalKinseyBarthSmoothing ',num2str(kbSmooth),'\n'...
        '    $_DM(',num2str(ID),') setExtrusionSolverAttribute NormalVolumeSmoothing ',num2str(volSmooth),'\n'...
        '    $_TMP(mode_1) run ',num2str(numLayers),'\n'...
        '$_TMP(mode_1) end\n'...
        'unset _TMP(mode_1)\n'...
        'unset _TMP(edge_1)\n']);
end